/* Перенос библиотеки в PVZ/models: совместимость сохранённых сцен. */
const legacyModelPaths: Record<string, string> = {
  "00_service_counter.glb": "service_counters/00_service_counter.glb",
  "02_employee_desk.glb": "tables/versions/models/02_employee_desk.glb",
  "03_monitor.glb": "monitors/versions/models/03_monitor.glb",
  "04_keyboard_mouse.glb": "keyboard_mouse/versions/models/04_keyboard_mouse.glb",
  "05_barcode_scanner.glb": "barcode_scanners/versions/models/05_barcode_scanner.glb",
  "06_storage_rack.glb": "storage_racks/versions/models/06_storage_rack.glb",
  "07_cardboard_boxes.glb": "cardboard_boxes/versions/models/07_cardboard_boxes.glb",
  "08_visitor_chair.glb": "chairs/versions/models/08_visitor_chair.glb",
  "09_inspection_table.glb": "tables/versions/models/09_inspection_table.glb",
  "10_fitting_room.glb": "fitting_rooms/versions/models/10_fitting_room.glb",
  "11_glass_entrance.glb": "doors/versions/models/11_glass_entrance.glb",
  "12_stockroom_door.glb": "doors/versions/models/12_stockroom_door.glb",
  "13_potted_plant.glb": "plants/versions/models/13_potted_plant.glb",
  "14_parcel_poster.glb": "posters/versions/models/14_parcel_poster.glb",
  "15_wall_clock.glb": "clocks/versions/models/15_wall_clock.glb",
  "16_floor_mirror.glb": "mirrors/versions/models/16_floor_mirror.glb",
  "17_large_trash_bin.glb": "bins/versions/models/17_large_trash_bin.glb",
  "18_small_wastebasket.glb": "bins/versions/models/18_small_wastebasket.glb",
  "19_stationery.glb": "stationery/versions/models/19_stationery.glb",
  "20_folding_cot.glb": "beds/versions/models/20_folding_cot.glb",
  "21_tea_table.glb": "tables/21_tea_table.glb",
  "22_jacket_hook.glb": "clothing_hooks/22_jacket_hook.glb",
  "23_backpack.glb": "backpacks/23_backpack.glb",
  "24_sneakers.glb": "shoes/24_sneakers.glb",
  "Concrete_Hemisphere.glb": "concrete_hemispheres/Concrete_Hemisphere.glb",
  "Moscow_Streetlamp.glb": "streetlamps/Moscow_Streetlamp.glb",
  "Residential_Building.glb": "buildings/Residential_Building.glb",
  "Samsung_SyncMaster_400b.glb": "monitors/Samsung_SyncMaster_400b.glb",
  "park_bench.glb": "benches/park_bench.glb",
  "trash_bin.glb": "bins/trash_bin.glb",
  "road/manhole/manhole.glb": "manholes/manhole.glb",
  "road/storm_drain/storm_drain.glb": "storm_drains/storm_drain.glb",
  "road/asphalt_section/asphalt_section.glb": "asphalt/asphalt_section.glb",
  "street/trash_bag/trash_bag.glb": "trash_bags/trash_bag.glb",
  "street/trash_bag/trash_bag_preview.glb": "trash_bags/trash_bag_preview.glb",
  "concepts/pvz_quarter_v2/PVZ_Quarter_v2.glb": "quarter/PVZ_Quarter_v2.glb"
};
export const migrateModelId = (id: string): string => legacyModelPaths[id] ?? id;
